### ISSUE TITLE
Can not collect logs because the node run out of disk space?

### ISSUE THREAD

**Issue by bvloi94** [Concordium/Testnet4-Challenges#707]
My vps run out of disk space and I can not download or running the binary to collect logs.

Do we have any solution to deal with this?

**Comment by Jasagredo** [comment]
When you say you cannot download the logs, you mean you cannot run `scp`?

Could you try doing the following (assuming your local machine is Linux/MacOS):
```
ssh user@vps 'docker logs concordium-client' > concordium-client.log
```
That will cat the logs through ssh.

You can also try downloading the docker logs raw file:
```
ssh -t user@vps 'sudo chmod 777 $(docker inspect --format='{{.LogPath}}' concordium-client)'
scp user@vps:$(ssh user@vps 'docker inspect --format='{{.LogPath}}' concordium-client') /some/path/in/your/machine
```

Note that this is intended for this use only as we are giving full permissions to a file that probably should have full permissions (`chmod 777`) as otherwise `scp` will refuse to copy it.

**Comment by concordium-cl** [comment]
@bvloi94: If you need the logs to submit to our baker challenges, please complete the submission without logs and refer to this issue in your PR. If you want your logs for other reasons, please follow @Jasagredo's instructions.

**Comment by bvloi94** [comment]
@concordium-cl, @Jasagredo  thank you very much, I will try your solution and give response later.

**Comment by concordium-cl** [comment]
@bvloi94: I see you submitted, so I'll close the issue now.
